FROM golang:1.19.0-alpine

WORKDIR /app
EXPOSE 3000

RUN apk update && apk add git
RUN go install -mod=mod github.com/githubnemo/CompileDaemon

COPY ./go.mod .
COPY ./go.sum .
RUN go mod download && go mod verify

COPY . .

ENTRYPOINT CompileDaemon --build="go build -o /out/app main.go" --command="/out/app"