version: "3"

volumes:
  postgresql:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgresql
    volumes:
      - postgresql:/data/postgresql
    ports:
      - "5432:5432"
